Repository Codeit-Sprint-Part-3-Team-8/Taskify, pull requests merged in 2024-12, with the labels that each got.

#3 [feat]: initial style 추가
  app/_styles/globals.css
  tailwind.config.ts
Labels: feature

#8 docs: 유저플로우 병합 추가
  docs/_keep
  docs/teskify.drawio.png
Labels: documentation

#9 [style] : Prettier, Lint 세팅
  .prettierrc
  app/_styles/globals.css
  docs/_keep
  docs/teskify.drawio.png
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feature

#15 feat: Modal common button 추가
  app/_components/Modal/ModalButton.tsx
  app/_components/_keep
Labels: feature

#14 [Fix] Tailwind CSS가 적용되지 않는 오류 해결
  .vscode/settings.json
  app/layout.tsx
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  tailwind.config.ts
Labels: bug

#12 [Feat] 회원가입 페이지 HTML 구조 구현
  .prettierrc
  .vscode/settings.json
  app/(routes)/signup/page.tsx
  app/_components/Modal/ModalButton.tsx
  app/_components/_keep
  app/layout.tsx
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  public/_keep
  public/logo-main.svg
  tailwind.config.ts
Labels: feature

#26 [Feat] 회원가입 페이지 UI 디자인 구현
  app/(routes)/signup/page.tsx
  public/images/icon-checkbox-active.png
  public/images/icon-checkbox-default.png
  public/images/logo-main.svg
Labels: feature

#31 [Feat] 사이드바 api 연결
  app/_components/sidebar/SideBar.tsx
  public/ic-crown.svg
Labels: feature

#33 [Feat] 회원가입 입력값 유효성 검사 구현
  app/(routes)/signup/AuthFooter.tsx
  app/(routes)/signup/AuthHeader.tsx
  app/(routes)/signup/CheckboxField.tsx
  app/(routes)/signup/InputField.tsx
  app/(routes)/signup/page.tsx
  app/(routes)/signup/signupType.ts
  app/(routes)/signup/validate.ts
  app/_lib/_keep
  app/_lib/validator.ts
Labels: feature

#22 랜딩페이지 기본작업 및 favicon 추가
  app/layout.tsx
  app/page.tsx
  public/images/contents/landing1.png
  public/images/contents/landing2.png
  public/images/contents/landing3.png
  public/images/contents/landing4.png
  public/images/contents/landing5.png
  public/images/contents/main.png
  public/images/icon/favicon.ico
  tsconfig.json
Labels: style

#39 [Fix] 메인페이지 이미지경로 수정
  app/page.tsx
Labels: bug

#35 [Feat] 사이드바 UI 디자인 구현
  app/_components/sidebar/SideBar.tsx
  public/images/icon/ic-crown.svg
  public/images/logo/logo-image.svg
  public/images/logo/logo-text.svg
  public/images/sidebar-plusbtn.svg
  public/main-logo.svg
Labels: feature

#40 [Feat] 랜딩 페이지 작업추가
  app/(routes)/landing/ContentBox.tsx
  app/(routes)/landing/Footer.tsx
  app/(routes)/landing/Header.tsx
  app/(routes)/landing/page.tsx
  app/fonts.ts
  app/page.tsx
  public/fonts/PretendardVariable.woff2
  public/images/contents/taskify.png
  public/images/icon/facebook.svg
  public/images/icon/instagram.svg
  public/images/icon/logo.svg
  public/images/icon/mail.svg
  tailwind.config.ts
Labels: style

#37 [Feat] 회원가입 페이지 기능 구현
  app/(routes)/signup/Modal.tsx
  app/(routes)/signup/page.tsx
  app/_hooks/_keep
  app/_hooks/useAsync.ts
  app/api/users.ts
Labels: feature

#41 [Feat] 사이드바 구현하기
  app/_components/sidebar/SideBar.tsx
  app/layout.tsx
  public/_keep
  public/images/icon/ic-crown.svg
  public/images/logo/logo-image.svg
  public/images/logo/logo-text.svg
  public/images/sidebar-plusbtn.svg
Labels: feature

#44 [Feat] 내 대시보드 페이지 구조 구현
  app/(routes)/mydashboard/DashboardList.tsx
  app/(routes)/mydashboard/page.tsx
  public/images/icon/ic-chip.svg
Labels: feature

#54 [Feat] 대쉬보드 페이지 Drag And Drop 기능 구현
  app/(routes)/dashboard/Dashboard.tsx
  app/(routes)/dashboard/Droppable.tsx
  app/(routes)/dashboard/Item.tsx
  app/(routes)/dashboard/MoveBetweenContainers.ts
  app/(routes)/dashboard/SortableItem.tsx
  app/(routes)/dashboard/array.ts
  app/(routes)/dashboard/page.tsx
  package-lock.json
  package.json
Labels: feature

#49 [Feat] 메인 랜딩페이지 네비게이션 바 구현하기
  app/_components/Navbar/HomeNavBar.tsx
  app/page.tsx
  public/images/logo/logo-image-white.svg
  public/images/logo/logo-text-white.svg
Labels: feature

#52 [Wontfix] 불필요한 리소스 제거
  app/_components/Modal/ModalButton.tsx
Labels: wontfix

#50 [Feat] 로그인 페이지 구현
  app/(routes)/login/loginType.ts
  app/(routes)/login/page.tsx
  app/(routes)/login/validate.ts
  app/(routes)/signup/page.tsx
  app/_components/Auth/AuthFooter.tsx
  app/_components/Auth/AuthHeader.tsx
  app/_components/Auth/InputField.tsx
  app/_components/Auth/Modal.tsx
  app/_hooks/useAsync.ts
  app/api/auth.ts
  app/api/axios.tsx
  app/api/users.ts
  app/context/AuthContext.tsx
  app/layout.tsx
Labels: feature

#61 [Feat] 내 대시보드 페이지 네비게이션 바 구현하기
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/MyDashboardNavBar.tsx
  app/_components/Sidebar/SideBar.tsx
  app/api/users.ts
  public/images/contents/default-profile.svg
Labels: feature

#57 [Feat] 폰트전역 추가
  app/layout.tsx
Labels: feature

#65 feat: 대시보드수정 상단카드작업
  app/(routes)/dashboard/[dashboardId]/edit/ColorSelectBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/MainContent.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/api/dashboard.ts
  public/images/icon/icon_arrow.svg
  public/images/icon/icon_check.svg
Labels: feature

#75 [Fix] 대시보드수정페이지 빌드오류 수정
  app/(routes)/dashboard/[dashboardId]/edit/ColorSelectBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/MainContent.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/api/dashboard.ts
  public/images/icon/icon_arrow.svg
  public/images/icon/icon_check.svg
Labels: bug

#71 [Feat] 대쉬보드 요구 데이터 fetching 작업 완료
  app/(routes)/dashboard/[id]/Dashboard.tsx
  app/(routes)/dashboard/[id]/Droppable.tsx
  app/(routes)/dashboard/[id]/MoveBetweenContainers.ts
  app/(routes)/dashboard/[id]/page.tsx
  app/api/cards.ts
  app/api/columns.ts
  app/api/dashboard.ts
  app/api/dashboardApi.ts
Labels: feature

#72 [Feat] 네비게이션 바 구현하기
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Navbar/Dropdown.tsx
  app/_components/Navbar/DropdownContent.tsx
  app/_components/Navbar/HomeNavBar.tsx
  app/_components/Navbar/MyDashboardNavBar.tsx
  app/_components/Navbar/NavBar.tsx
  app/_components/Navbar/Profile.tsx
  app/_components/Sidebar/SideBar.tsx
  app/api/navbar.ts
  public/images/contents/default-profile.svg
  public/images/icon/ic-plusbtn.svg
  public/images/icon/ic-setting.svg
  public/images/logo/logo-image-white.svg
  public/images/logo/logo-text-white.svg
Labels: feature

#78 [Feat] 공용 API와 Type 구현
  app/(routes)/signup/page.tsx
  app/_types/_keep
  app/_types/auth.type.ts
  app/_types/cards.type.ts
  app/_types/columns.type.ts
  app/_types/comments.type.ts
  app/_types/dashboards.type.ts
  app/_types/invitations.type.ts
  app/_types/members.type.ts
  app/_types/users.type.ts
  app/api/auth.api.ts
  app/api/auth.ts
  app/api/cards.api.ts
  app/api/columns.api.ts
  app/api/comments.api.ts
  app/api/dashboards.api.ts
  app/api/invitations.api.ts
  app/api/member.api.ts
  app/api/users.api.ts
  app/api/users.ts
  app/context/AuthContext.tsx
Labels: feature

#76 [Feat] 로그인/회원가입 페이지 유저 인터렉션 구현
  app/(routes)/login/page.tsx
  app/(routes)/signup/page.tsx
  app/(routes)/signup/validate.ts
  app/_components/Auth/AuthHeader.tsx
  app/_components/Auth/InputField.tsx
  public/images/icon/icon-visibility-off.svg
  public/images/icon/icon-visibility-on.svg
Labels: feature

#69 [feat]: 대시보드, 컬럼, 초대하기 모달 & Modal API 구현
  app/(routes)/dashboard/CreateColumnModal.tsx
  app/(routes)/dashboard/EditColumnModal.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/mydashboard/CreateDashboardModal.tsx
  app/_components/Button/Button.tsx
  app/_components/Modals/GenericModal.tsx
  app/_components/Modals/Invite/InviteModal.tsx
  app/_components/Modals/ModalInput.tsx
  app/api/types.ts
  app/utils/error.ts
  public/images/icon/check.svg
Labels: feature

#81 [Feat] 내 대시보드 리스트 구현하기
  app/(routes)/mydashboard/DashboardList.tsx
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Navbar/DropdownContent.tsx
  app/_components/Navbar/MyDashboardNavBar.tsx
  app/api/mydashboard.ts
  public/images/icon/ic-blackarrow.svg
  public/images/icon/ic-leftarrow-gray.svg
  public/images/icon/ic-rightarrow-gray.svg
Labels: feature

#84 [Feat] drag-end시 undefined가 생기는 오류 수정
  app/(routes)/dashboard/[id]/Dashboard.tsx
  app/(routes)/dashboard/[id]/Droppable.tsx
  app/(routes)/dashboard/[id]/MoveBetweenContainers.ts
  app/api/cards.ts
Labels: bug

#92 fix: ModalInput 초기값 설정 오류 수정
  app/_components/Modals/ModalInput.tsx
Labels: bug

#93 [Feat] 63--id-page 브랜치 병합
  app/(routes)/dashboard/Dashboard.tsx
  app/(routes)/dashboard/MoveBetweenContainers.ts
  app/(routes)/dashboard/[id]/Dashboard.tsx
  app/(routes)/dashboard/[id]/Droppable.tsx
  app/(routes)/dashboard/[id]/Item.tsx
  app/(routes)/dashboard/[id]/MoveBetweenContainers.ts
  app/(routes)/dashboard/[id]/SortableItem.tsx
  app/(routes)/dashboard/[id]/array.ts
  app/(routes)/dashboard/[id]/page.tsx
  app/(routes)/dashboard/page.tsx
  app/api/cards.ts
  app/api/columns.ts
  app/api/dashboard.ts
Labels: feature

#94 [Feat] 계정 관리 페이지 구조 구현
  app/(routes)/mypage/PasswordForm.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/page.tsx
Labels: feature

#86 [Feat] 대시보드수정 중간영역 구성원카드구현
  app/(routes)/dashboard/[dashboardId]/edit/ColorSelectBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/MainContent.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyList.tsx
  app/(routes)/dashboard/[dashboardId]/edit/Pagenation.tsx
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/_styles/globals.css
Labels: feature

#97 [Feat] 사이드바 구현하기
  app/_components/Sidebar/SideBar.tsx
  public/images/icon/ic-leftarrow-gray.svg
  public/images/icon/ic-rightarrow-gray.svg
Labels: feature

#99 [Feat] 공통 api및 타입 적용, [id] -> [dashboardId]로 동적 라우팅 경로 변경
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/MoveBetweenContainers.ts
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/(routes)/dashboard/[dashboardId]/array.ts
  app/(routes)/dashboard/[dashboardId]/page.tsx
  app/_types/columns.type.ts
  app/api/cards.ts
  app/api/columns.ts
  app/api/dashboard.ts
Labels: feature

#98 [Feat] 대시보드수정 상단, 중간영역 구현
  app/(routes)/dashboard/[dashboardId]/edit/ColorSelectBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/MainContent.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyList.tsx
  app/(routes)/dashboard/[dashboardId]/edit/Pagenation.tsx
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/_styles/globals.css
Labels: feature

#101 [Feat] 대시보드 페이지 변경 사항 반영
  app/(routes)/dashboard/Dashboard.tsx
  app/(routes)/dashboard/MoveBetweenContainers.ts
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/MoveBetweenContainers.ts
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/(routes)/dashboard/[dashboardId]/array.ts
  app/(routes)/dashboard/[dashboardId]/page.tsx
  app/(routes)/dashboard/page.tsx
  app/_types/columns.type.ts
  app/api/dashboard.ts
Labels: feature

#100 [Feat] 계정 관리 페이지 정적 디자인 구현
  app/(routes)/mypage/ImageInputField.tsx
  app/(routes)/mypage/PasswordForm.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/page.tsx
  app/_components/Auth/InputField.tsx
  public/images/icon/icon-plus-purple.png
  tailwind.config.ts
Labels: feature

#102 [Feat] 내 대시보드 페이지 구현하기
  app/(routes)/mydashboard/DashboardList.tsx
  app/(routes)/mydashboard/InvitationsDashboardList.tsx
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Navbar/DropdownContent.tsx
  app/_components/Navbar/MyDashboardNavBar.tsx
  app/_components/Sidebar/SideBar.tsx
  app/api/mydashboard.ts
  public/images/icon/ic-blackarrow.svg
  public/images/icon/ic-invite.svg
Labels: feature

#106 [Feat] 네비게이션 바 구현하기
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Navbar/HomeNavBar.tsx
  app/_components/Sidebar/SideBar.tsx
  package-lock.json
Labels: feature

#108 [Feat] 사이드바 페이지에 따른 배경색 변경
  app/_components/Sidebar/SideBar.tsx
Labels: feature

#112 [Feat] 프로필 이미지 업로드 및 미리보기 기능 구현
  app/(routes)/mypage/ImageInputField.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/page.tsx
  app/_components/Auth/InputField.tsx
  app/_types/users.type.ts
  app/api/users.api.ts
  next.config.ts
Labels: feature

#118 [Feat] 프로필 변경 구현
  app/(routes)/mypage/ImageInputField.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/page.tsx
  app/(routes)/mypage/types.ts
  app/(routes)/mypage/validate.ts
  app/(routes)/signup/validate.ts
  app/_lib/validator.ts
Labels: feature

#119 feat: 대쉬보드 컨테이너 반응형 레이아웃 구현
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/_styles/globals.css
Labels: feature

#122 feat. 대시보드수정 하단영역 구현
  app/(routes)/dashboard/[dashboardId]/edit/ColorSelectBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/InviteList.tsx
  app/(routes)/dashboard/[dashboardId]/edit/InviteModal.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyList.tsx
  app/(routes)/dashboard/[dashboardId]/edit/Pagenation.tsx
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/_styles/globals.css
  public/images/icon/ic-plusbtn-white.svg
Labels: feature

#115 feat: 할 일 카드 생성 모달 기능 구현
  app/_components/Button/Button.tsx
  app/_components/Calendar/Calendar.tsx
  app/_components/Calendar/CalendarButton.tsx
  app/_components/Dropdown/Dropdown.tsx
  app/_components/Modals/Dashboard/CreateTodoModal.tsx
  app/_components/Modals/ImageUpload.tsx
  app/_components/Modals/ModalInput.tsx
  app/lib/utils.ts
  components.json
  package-lock.json
  package.json
  public/images/icon/ic-dropdown-arrow.svg
  tailwind.config.ts
Labels: feature

#124 [Feat] 비밀번호 변경 기능 구현
  app/(routes)/mypage/PasswordForm.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/types.ts
  app/(routes)/mypage/validate.ts
  app/api/auth.api.ts
Labels: feature

#121 [Feat] 초대받은 대시보드 리스트 구현하기
  app/(routes)/mydashboard/InvitationTable.tsx
  app/(routes)/mydashboard/InvitationsDashboard.tsx
  app/(routes)/mydashboard/InvitationsDashboardList.tsx
  app/(routes)/mydashboard/SearchBar.tsx
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/MyDashboardNavBar.tsx
  app/api/invitations.api.ts
  next.config.ts
  public/images/icon/ic-search.svg
Labels: feature

#125 대시보드수정 페이지구현
  app/(routes)/dashboard/[dashboardId]/edit/ColorSelectBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/InviteList.tsx
  app/(routes)/dashboard/[dashboardId]/edit/InviteModal.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/dashboard/[dashboardId]/edit/ModifyList.tsx
  app/(routes)/dashboard/[dashboardId]/edit/Pagenation.tsx
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/_styles/globals.css
  public/images/icon/ic-plusbtn-white.svg
Labels: feature

#129 faet: 할 일 생성/수정 컴포넌트에 사용될 공통 컴포넌트 제작
  app/(routes)/mydashboard/CreateDashboardModal.tsx
  app/_components/Calendar/Calendar.tsx
  app/_components/Modals/Dashboard/TodoFormContent.tsx
  app/_components/Modals/Dashboard/TodoFormFooter.tsx
  app/_components/Modals/GenericModal.tsx
  app/_components/Modals/ImageUpload.tsx
  app/_components/Modals/ModalInput.tsx
  app/_types/cards.type.ts
  app/_types/todo-prop.type.ts
Labels: refactor

#131 feat: 할 일 수정 모달 구현
  app/_components/Modals/Dashboard/CreateTodoModal.tsx
  app/_components/Modals/Dashboard/EditTodoModal.tsx
Labels: feature

#133 [Refactor] 나의 대시보드 리팩토링
  app/(routes)/mydashboard/DashboardList.tsx
  app/(routes)/mydashboard/InvitationsDashboard.tsx
  app/(routes)/mydashboard/page.tsx
Labels: refactor

#130 대쉬보드 컨테이너 스타일링(컬럼 생성 버튼, 카드 생성 버튼, 컬럼 수정 버튼)
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/_styles/globals.css
  public/images/icon/ic-plusbtn-purple.svg
Labels: style

#139 대쉬보드 페이지 기본 스타일링 작업
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/_components/Sidebar/SideBar.tsx
  app/_styles/globals.css
  public/images/icon/ic-plusbtn-purple.svg
Labels: style

#135 [Feat] 대시보드 초대 수락시 해당 대시보드 페이지로 이동
  app/(routes)/mydashboard/InvitationTable.tsx
  app/(routes)/mydashboard/InvitationsDashboard.tsx
Labels: feature

#137 [Refactor] 네비게이션 바 리팩토링
  app/_components/Navbar/DashboardNavBar.tsx
Labels: refactor

#145 [Feat] 계정 관리 페이지 구현
  app/(routes)/login/page.tsx
  app/(routes)/mypage/ImageInputField.tsx
  app/(routes)/mypage/PasswordForm.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/page.tsx
  app/(routes)/mypage/types.ts
  app/(routes)/mypage/validate.ts
  app/(routes)/signup/validate.ts
  app/_components/Auth/InputField.tsx
  app/_lib/validator.ts
  app/_types/users.type.ts
  app/api/auth.api.ts
  app/api/users.api.ts
  app/context/AuthContext.tsx
  next.config.ts
  public/images/icon/icon-plus-purple.png
  tailwind.config.ts
Labels: feature

#143 [Feat] 나의 대시보드 페이지 리스트 Skeleton 디자인 추가
  app/(routes)/mydashboard/DashboardList.tsx
  app/(routes)/mydashboard/InvitationSkeleton.tsx
  app/(routes)/mydashboard/InvitationsDashboard.tsx
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/DashboardNavBar.tsx
  public/images/icon/ic-spin.svg
Labels: feature

#141 [Feat] 대쉬보드 카드 드래그 api 구현
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/page.tsx
  app/_types/cards.type.ts
Labels: feature

#146 [Feat] 나의 대시보드 페이지 구현하기
  app/(routes)/mydashboard/DashboardList.tsx
  app/(routes)/mydashboard/InvitationSkeleton.tsx
  app/(routes)/mydashboard/InvitationTable.tsx
  app/(routes)/mydashboard/InvitationsDashboard.tsx
  app/(routes)/mydashboard/InvitationsDashboardList.tsx
  app/(routes)/mydashboard/SearchBar.tsx
  app/(routes)/mydashboard/page.tsx
  app/_components/Navbar/MyDashboardNavBar.tsx
  app/api/invitations.api.ts
  public/images/icon/ic-search.svg
  public/images/icon/ic-spin.svg
Labels: feature

#148 [Bug] 로그인/회원가입 페이지 접속 시, 리다이렉트 전 레이아웃이 렌더링 되던 문제 해결
  app/(routes)/login/page.tsx
  app/(routes)/mypage/page.tsx
  app/(routes)/signup/page.tsx
  app/_components/Auth/Navigate.tsx
  app/context/AuthContext.tsx
Labels: bug, feature

#151 [Feat] Container 컴포넌트 구현
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Sidebar/SideBar.tsx
  app/_components/layout/Container.tsx
  app/context/AuthContext.tsx
Labels: bug, feature, refactor

#154 [Feat] 대쉬보드 페이지에 컬럼 버튼 동작 추가
  app/(routes)/dashboard/CreateColumnModal.tsx
  app/(routes)/dashboard/EditColumnModal.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
Labels: feature

#157 [Feat] 대쉬보드 드래그 아이템 스타일링
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/_styles/globals.css
  public/images/contents/default-preview-card.svg
  public/images/icon/ic-calendar.svg
Labels: feature

#158 [Feat] 로딩 애니메이션 컴포넌트 추가
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/DashboardLoading.tsx
  app/(routes)/dashboard/[dashboardId]/DotLoader.tsx
  tailwind.config.ts
Labels: feature

#161 할 일 모달 관련 컴포넌트 리펙토링
  app/_components/Modals/Dashboard/TodoFormContent.tsx
  app/_components/Modals/GenericModal.tsx
  app/_components/Modals/ModalInput.tsx
Labels: refactor

#168 대쉬보드 페이지 dev 병합
  app/(routes)/dashboard/CreateColumnModal.tsx
  app/(routes)/dashboard/EditColumnModal.tsx
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/DashboardLoading.tsx
  app/(routes)/dashboard/[dashboardId]/DotLoader.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/(routes)/dashboard/[dashboardId]/page.tsx
  app/_styles/globals.css
  app/_types/cards.type.ts
  public/images/contents/default-preview-card.svg
  public/images/icon/ic-calendar.svg
  public/images/icon/ic-plusbtn-purple.svg
  tailwind.config.ts
Labels: feature

#169 [Feat] 사이드바 스켈레톤 코드 구현하기
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/_components/Sidebar/SideBar.tsx
  app/_components/Sidebar/SideBarSkeleton.tsx
  package-lock.json
Labels: feature

#167 할 일 관련 모달
  app/(routes)/dashboard/[dashboardId]/CreateTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
  app/(routes)/mydashboard/CreateDashboardModal.tsx
  app/_components/Button/Button.tsx
  app/_components/Calendar/Calendar.tsx
  app/_components/Calendar/CalendarButton.tsx
  app/_components/Dropdown/Dropdown.tsx
  app/_components/Modals/DashboardModal/CommentList.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/Modals/DashboardModal/TodoFormFooter.tsx
  app/_components/Modals/GenericModal.tsx
  app/_components/Modals/ImageUpload.tsx
  app/_components/Modals/ModalInput.tsx
  app/_components/UserProfile/UserProfile.tsx
  app/_hooks/useCommentList.ts
  app/_hooks/useIntersectionObserver.ts
  app/_lib/utils.ts
  app/_types/cards.type.ts
  app/_types/comments.type.ts
  app/_types/todo-prop.type.ts
  components.json
  package-lock.json
  package.json
  public/images/icon/ic-dropdown-arrow.svg
  tailwind.config.ts
Labels: feature

#171 [Feat] 대쉬보드 페이지 할 일 카드 생성/수정/삭제 기능 연결
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
  app/(routes)/dashboard/[dashboardId]/page.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/UserProfile/UserProfile.tsx
  app/_types/cards.type.ts
Labels: feature

#173 사이드바 dev브랜치 병합
  app/(routes)/dashboard/[dashboardId]/edit/page.tsx
  app/_components/Sidebar/SideBar.tsx
  app/_components/Sidebar/SideBarSkeleton.tsx
  app/_types/cards.type.ts
  package-lock.json
Labels: feature

#179 대쉬보드 변경사항 반영
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
  app/(routes)/dashboard/[dashboardId]/page.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/UserProfile/UserProfile.tsx
  app/_types/cards.type.ts
Labels: feature

#174 feat: 할 일 카드 모달 반응형 디자인 구현
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
  app/_components/Modals/DashboardModal/CommentList.tsx
Labels: style

#183 [Fix] QA 개선 사항 반영
  app/(routes)/mypage/PasswordForm.tsx
  app/(routes)/mypage/ProfileForm.tsx
  app/(routes)/mypage/page.tsx
  app/_components/Auth/Modal.tsx
  app/_components/layout/Container.tsx
  app/context/AuthContext.tsx
Labels: bug

#178 refactor: 모달 스타일 및 반응형
  app/(routes)/mydashboard/CreateDashboardModal.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/Modals/GenericModal.tsx
Labels: refactor

#187 [Fix] DELETE 요청 성공 시 true 반환
  app/api/cards.api.ts
  app/api/columns.api.ts
  app/api/comments.api.ts
  app/api/dashboards.api.ts
  app/api/member.api.ts
Labels: bug

#188 fix: 이미지 초기값 수정 & 생성/수정 모달에서 userId request로 전달
  app/(routes)/dashboard/[dashboardId]/CreateTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/Modals/ImageUpload.tsx
Labels: bug

#189 refactor: 컬럼 삭제 버튼 클릭 시 alert 창 안 나타나도록 수정
  app/(routes)/dashboard/EditColumnModal.tsx
Labels: refactor

#195 [Fix] 카드 이미지 생성 api 타입 및 헤더 수정
  app/_types/columns.type.ts
  app/api/columns.api.ts
Labels: bug

#192 대쉬보드 할 일 카드 생성/삭제/수정 시 상태 업데이트
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
Labels: feature

#198 대쉬보드 브랜치 병합
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
Labels: feature

#196 Dot Loader delay 오류 수정
  app/(routes)/dashboard/[dashboardId]/DotLoader.tsx
Labels: bug

#197 [Fix] 입력 요소 outline 수정
  app/(routes)/dashboard/[dashboardId]/edit/ModifyBox.tsx
  app/(routes)/mydashboard/SearchBar.tsx
  app/_components/Dropdown/Dropdown.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/Modals/ModalInput.tsx
Labels: bug

#199 [Fix] 비밀번호 편집 유효성 경고 문구 수정
  app/(routes)/landing/page.tsx
  app/(routes)/mypage/page.tsx
  app/(routes)/mypage/validate.ts
  app/_components/Navbar/MyDashboardNavBar.tsx
Labels: bug

#201 대쉬보드 변경사항 반영
  app/(routes)/dashboard/[dashboardId]/CreateTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_components/Modals/ImageUpload.tsx
Labels: bug

#202 [Feat] 프로필 이미지 cover 속성 추가
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Navbar/Profile.tsx
Labels: feature

#205 [Fix] 페이지네이션 페이지 default값 수정
  app/(routes)/mydashboard/DashboardList.tsx
Labels: bug

#206 [Feat] 할 일 카드 생성/수정 모달에서 오버레이 클릭해도 창이 안 닫히도록 설정
  app/(routes)/dashboard/[dashboardId]/CreateTodoModal.tsx
  app/(routes)/dashboard/[dashboardId]/EditTodoModal.tsx
  app/_components/Modals/GenericModal.tsx
Labels: feature

#207 refactor: 태그 글자 over flow 처리 구현
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
Labels: refactor

#208 [Feat] 할 일 카드 댓글 불러오기 및 생성 구현
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/TodoCardModal.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalComment.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalContent.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalHeader.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/index.tsx
  app/_components/UserProfile/UserProfile.tsx
Labels: feature

#209 [Feat] 댓글 수정/삭제 기능 구현
  app/(routes)/dashboard/[dashboardId]/Dashboard.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalComment.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalContent.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalHeader.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalInfo.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalTags.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/index.tsx
Labels: feature

#210 전반적인 버튼, 모달 스타일 개선
  app/(routes)/dashboard/[dashboardId]/CreateCardButton.tsx
  app/(routes)/dashboard/[dashboardId]/CreateColumnButton.tsx
  app/(routes)/dashboard/[dashboardId]/Droppable.tsx
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/SortableItem.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/index.tsx
  app/(routes)/mydashboard/DashboardList.tsx
  app/_components/Modals/GenericModal.tsx
  app/_components/Navbar/DashboardNavBar.tsx
  app/_components/Sidebar/SideBar.tsx
  package-lock.json
  tailwind.config.ts
Labels: style

#211 Hotfix/etc
  app/(routes)/dashboard/[dashboardId]/Item.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalComment.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/ModalContent.tsx
  app/(routes)/dashboard/[dashboardId]/_TodoCardModal/index.tsx
  app/(routes)/landing/page.tsx
  app/_components/Dropdown/Dropdown.tsx
  app/_components/Modals/DashboardModal/TodoFormContent.tsx
  app/_constants/_keep
  app/_hooks/useResize.ts
  app/_lib/error.ts
Labels: bug

#212 태그 크기 이탈 오류 해결
  app/(routes)/dashboard/[dashboardId]/Item.tsx
Labels: bug
